# Generated by Django 4.2.4 on 2023-08-24 01:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_question_point_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('teacher', '講師'), ('student', '生徒')], default='student', max_length=200),
        ),
        migrations.AlterField(
            model_name='matching',
            name='time',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '月'), (2, '火'), (3, '水'), (4, '木'), (5, '金'), (6, '土'), (7, '日')], max_length=200),
        ),
    ]
