# Generated by Django 4.2.2 on 2023-08-28 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_question_options_answer_updated_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matching',
            new_name='MatchingStudent',
        ),
        migrations.CreateModel(
            name='MatchingTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_min', models.IntegerField(null=True)),
                ('salary_max', models.IntegerField(null=True)),
                ('time', multiselectfield.db.fields.MultiSelectField(choices=[(1, '月'), (2, '火'), (3, '水'), (4, '木'), (5, '金'), (6, '土'), (7, '日')], max_length=200, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
