# Generated by Django 4.2.2 on 2023-08-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_matching_matchingstudent_matchingteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingteacher',
            old_name='salary_max',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='matchingteacher',
            name='salary_min',
        ),
    ]
