# Generated by Django 4.2.3 on 2023-08-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_review'),
        ('base', '0011_rename_salary_max_matchingteacher_salary_and_more'),
    ]

    operations = [
    ]
