# Generated by Django 4.2.4 on 2023-08-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_merge_20230829_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchingTeacher',
            new_name='Matching',
        ),
        migrations.DeleteModel(
            name='MatchingStudent',
        ),
    ]
