# Generated by Django 4.2.4 on 2023-08-30 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_matchingteacher_matching_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='point',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='review',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.topic'),
        ),
        migrations.AddField(
            model_name='review',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', '講師'), ('student', '生徒')], default='student', max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
    ]
