# Generated by Django 4.2.4 on 2023-08-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_review_teacher_alter_review_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
