# Generated by Django 4.2.4 on 2023-08-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_merge_20230830_1123'),
        ('base', '0013_userinfo'),
        ('base', '0018_delete_point'),
    ]

    operations = [
    ]
