# Generated by Django 4.2.2 on 2023-08-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_merge_20230830_1845'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='matching',
            name='matching_count',
            field=models.IntegerField(default=0),
        ),
    ]
