# Generated by Django 4.2.4 on 2023-08-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_merge_20230830_1845'),
    ]

    operations = [
        
    ]
