# Generated by Django 4.2.4 on 2023-08-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_contact_matching_matching_count'),
        ('base', '0022_alter_user_age'),
    ]

    operations = [
    ]
